// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/trust/v1/trust.proto

package apiv1

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrustService_SubmitAttestation_FullMethodName  = "/sigil.trust.v1.TrustService/SubmitAttestation"
	TrustService_GetToolTrust_FullMethodName       = "/sigil.trust.v1.TrustService/GetToolTrust"
	TrustService_GetAttestation_FullMethodName     = "/sigil.trust.v1.TrustService/GetAttestation"
	TrustService_ListAttestations_FullMethodName   = "/sigil.trust.v1.TrustService/ListAttestations"
	TrustService_ListTopTools_FullMethodName       = "/sigil.trust.v1.TrustService/ListTopTools"
	TrustService_RetractAttestation_FullMethodName = "/sigil.trust.v1.TrustService/RetractAttestation"
)

// TrustServiceClient is the client API for TrustService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TrustService provides tool trust queries and attestation submission.
//
// Privacy design:
//   - ListAttestations filters by tool, NOT by attester. Attester DIDs are
//     redacted in list responses to prevent cross-tool enumeration of usage
//     patterns.
//   - GetAttestation returns full details (including attester DID) for a
//     single attestation by ID, preserving independent verifiability.
//   - A future GetMyAttestations RPC (authenticated) can be added when needed.
type TrustServiceClient interface {
	// SubmitAttestation records a signed tool attestation.
	//
	// Timestamp acceptance window: issued_at must be within 5 minutes in the
	// future or 24 hours in the past relative to server time.
	//
	// Only did:key attesters are accepted initially.
	//
	// Rate limit: 50 attestations per DID per hour.
	SubmitAttestation(ctx context.Context, in *SubmitAttestationRequest, opts ...grpc.CallOption) (*SubmitAttestationResponse, error)
	// GetToolTrust returns the computed trust digest for a tool.
	// Unknown tools return a zero-value digest (not NOT_FOUND).
	GetToolTrust(ctx context.Context, in *GetToolTrustRequest, opts ...grpc.CallOption) (*GetToolTrustResponse, error)
	// GetAttestation retrieves a single attestation by ID with full details
	// including the attester DID (for independent verification).
	GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error)
	// ListAttestations returns attestations for a tool with attester DIDs
	// redacted to prevent enumeration.
	ListAttestations(ctx context.Context, in *ListAttestationsRequest, opts ...grpc.CallOption) (*ListAttestationsResponse, error)
	// ListTopTools returns tools ranked by trust score within a time window.
	ListTopTools(ctx context.Context, in *ListTopToolsRequest, opts ...grpc.CallOption) (*ListTopToolsResponse, error)
	// RetractAttestation soft-deletes an attestation. Only the original attester
	// can retract, verified by Ed25519 signature over a canonical deletion payload.
	RetractAttestation(ctx context.Context, in *RetractAttestationRequest, opts ...grpc.CallOption) (*RetractAttestationResponse, error)
}

type trustServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrustServiceClient(cc grpc.ClientConnInterface) TrustServiceClient {
	return &trustServiceClient{cc}
}

func (c *trustServiceClient) SubmitAttestation(ctx context.Context, in *SubmitAttestationRequest, opts ...grpc.CallOption) (*SubmitAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAttestationResponse)
	err := c.cc.Invoke(ctx, TrustService_SubmitAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) GetToolTrust(ctx context.Context, in *GetToolTrustRequest, opts ...grpc.CallOption) (*GetToolTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolTrustResponse)
	err := c.cc.Invoke(ctx, TrustService_GetToolTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttestationResponse)
	err := c.cc.Invoke(ctx, TrustService_GetAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) ListAttestations(ctx context.Context, in *ListAttestationsRequest, opts ...grpc.CallOption) (*ListAttestationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttestationsResponse)
	err := c.cc.Invoke(ctx, TrustService_ListAttestations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) ListTopTools(ctx context.Context, in *ListTopToolsRequest, opts ...grpc.CallOption) (*ListTopToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopToolsResponse)
	err := c.cc.Invoke(ctx, TrustService_ListTopTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) RetractAttestation(ctx context.Context, in *RetractAttestationRequest, opts ...grpc.CallOption) (*RetractAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractAttestationResponse)
	err := c.cc.Invoke(ctx, TrustService_RetractAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
