// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/trust/v1/trust.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitAttestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attestation ID (ULID). Acts as idempotency key: duplicate IDs with same
	// content return ALREADY_EXISTS; different content returns ABORTED.
	AttestationId string `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	// Attester DID (must be did:key).
	AttesterDid string `protobuf:"bytes,2,opt,name=attester_did,json=attesterDid,proto3" json:"attester_did,omitempty"`
	// Tool URI (e.g. "mcp://github.com/user/repo").
	ToolUri string `protobuf:"bytes,3,opt,name=tool_uri,json=toolUri,proto3" json:"tool_uri,omitempty"`
	// Outcome: "success" or "negative".
	Outcome string `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// Optional claims (max 32 keys, 8 KB total, 64 byte keys, 1 KB values).
	Claims map[string]string `protobuf:"bytes,5,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Payload version string.
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// Ed25519 signature over the canonical attestation payload.
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// When the attestation was issued by the attester.
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAttestationRequest) Reset() {
	*x = SubmitAttestationRequest{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAttestationRequest) ProtoMessage() {}

func (x *SubmitAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAttestationRequest.ProtoReflect.Descriptor instead.
func (*SubmitAttestationRequest) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitAttestationRequest) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *SubmitAttestationRequest) GetAttesterDid() string {
	if x != nil {
		return x.AttesterDid
	}
	return ""
}

func (x *SubmitAttestationRequest) GetToolUri() string {
	if x != nil {
		return x.ToolUri
	}
	return ""
}

func (x *SubmitAttestationRequest) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *SubmitAttestationRequest) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *SubmitAttestationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SubmitAttestationRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SubmitAttestationRequest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type SubmitAttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttestationId string                 `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	Deduplicated  bool                   `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"` // true when a matching positive already existed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAttestationResponse) Reset() {
	*x = SubmitAttestationResponse{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAttestationResponse) ProtoMessage() {}

func (x *SubmitAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAttestationResponse.ProtoReflect.Descriptor instead.
func (*SubmitAttestationResponse) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitAttestationResponse) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *SubmitAttestationResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type GetToolTrustRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool URI to look up.
	ToolUri       string `protobuf:"bytes,1,opt,name=tool_uri,json=toolUri,proto3" json:"tool_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolTrustRequest) Reset() {
	*x = GetToolTrustRequest{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolTrustRequest) ProtoMessage() {}

func (x *GetToolTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolTrustRequest.ProtoReflect.Descriptor instead.
func (*GetToolTrustRequest) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{2}
}

func (x *GetToolTrustRequest) GetToolUri() string {
	if x != nil {
		return x.ToolUri
	}
	return ""
}

type GetToolTrustResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Score             float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	TotalAttestations int32                  `protobuf:"varint,2,opt,name=total_attestations,json=totalAttestations,proto3" json:"total_attestations,omitempty"`
	UniqueAttesters   int32                  `protobuf:"varint,3,opt,name=unique_attesters,json=uniqueAttesters,proto3" json:"unique_attesters,omitempty"`
	SuccessRate       float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	LastActive        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	FirstSeen         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	Provisional       bool                   `protobuf:"varint,7,opt,name=provisional,proto3" json:"provisional,omitempty"`
	ComputedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	VersionsAttested  int32                  `protobuf:"varint,9,opt,name=versions_attested,json=versionsAttested,proto3" json:"versions_attested,omitempty"` // count of distinct non-empty versions
	LatestVersion     string                 `protobuf:"bytes,10,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`          // most recently attested version string
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetToolTrustResponse) Reset() {
	*x = GetToolTrustResponse{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolTrustResponse) ProtoMessage() {}

func (x *GetToolTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolTrustResponse.ProtoReflect.Descriptor instead.
func (*GetToolTrustResponse) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{3}
}

func (x *GetToolTrustResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GetToolTrustResponse) GetTotalAttestations() int32 {
	if x != nil {
		return x.TotalAttestations
	}
	return 0
}

func (x *GetToolTrustResponse) GetUniqueAttesters() int32 {
	if x != nil {
		return x.UniqueAttesters
	}
	return 0
}

func (x *GetToolTrustResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *GetToolTrustResponse) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *GetToolTrustResponse) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *GetToolTrustResponse) GetProvisional() bool {
	if x != nil {
		return x.Provisional
	}
	return false
}

func (x *GetToolTrustResponse) GetComputedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ComputedAt
	}
	return nil
}

func (x *GetToolTrustResponse) GetVersionsAttested() int32 {
	if x != nil {
		return x.VersionsAttested
	}
	return 0
}

func (x *GetToolTrustResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

type GetAttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttestationId string                 `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttestationRequest) Reset() {
	*x = GetAttestationRequest{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationRequest) ProtoMessage() {}

func (x *GetAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationRequest.ProtoReflect.Descriptor instead.
func (*GetAttestationRequest) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttestationRequest) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

type GetAttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestation   *Attestation           `protobuf:"bytes,1,opt,name=attestation,proto3" json:"attestation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttestationResponse) Reset() {
	*x = GetAttestationResponse{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttestationResponse) ProtoMessage() {}

func (x *GetAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttestationResponse.ProtoReflect.Descriptor instead.
func (*GetAttestationResponse) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttestationResponse) GetAttestation() *Attestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

type ListAttestationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: tool URI to list attestations for.
	ToolUri string `protobuf:"bytes,1,opt,name=tool_uri,json=toolUri,proto3" json:"tool_uri,omitempty"`
	// Optional time range filters.
	After         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttestationsRequest) Reset() {
	*x = ListAttestationsRequest{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttestationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttestationsRequest) ProtoMessage() {}

func (x *ListAttestationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttestationsRequest.ProtoReflect.Descriptor instead.
func (*ListAttestationsRequest) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{6}
}

func (x *ListAttestationsRequest) GetToolUri() string {
	if x != nil {
		return x.ToolUri
	}
	return ""
}

func (x *ListAttestationsRequest) GetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ListAttestationsRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ListAttestationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAttestationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAttestationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestations  []*RedactedAttestation `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttestationsResponse) Reset() {
	*x = ListAttestationsResponse{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttestationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttestationsResponse) ProtoMessage() {}

func (x *ListAttestationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttestationsResponse.ProtoReflect.Descriptor instead.
func (*ListAttestationsResponse) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{7}
}

func (x *ListAttestationsResponse) GetAttestations() []*RedactedAttestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *ListAttestationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListTopToolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time window in days (default 30).
	WindowDays int32 `protobuf:"varint,1,opt,name=window_days,json=windowDays,proto3" json:"window_days,omitempty"`
	// Max tools to return (default 50, max 100).
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Minimum age in days: tools must have first attestation older than this
	// to appear on the leaderboard (prevents gaming by new tools).
	MinAgeDays    int32 `protobuf:"varint,3,opt,name=min_age_days,json=minAgeDays,proto3" json:"min_age_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopToolsRequest) Reset() {
	*x = ListTopToolsRequest{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopToolsRequest) ProtoMessage() {}

func (x *ListTopToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopToolsRequest.ProtoReflect.Descriptor instead.
func (*ListTopToolsRequest) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{8}
}

func (x *ListTopToolsRequest) GetWindowDays() int32 {
	if x != nil {
		return x.WindowDays
	}
	return 0
}

func (x *ListTopToolsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTopToolsRequest) GetMinAgeDays() int32 {
	if x != nil {
		return x.MinAgeDays
	}
	return 0
}

type ListTopToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolSummary         `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopToolsResponse) Reset() {
	*x = ListTopToolsResponse{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopToolsResponse) ProtoMessage() {}

func (x *ListTopToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopToolsResponse.ProtoReflect.Descriptor instead.
func (*ListTopToolsResponse) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{9}
}

func (x *ListTopToolsResponse) GetTools() []*ToolSummary {
	if x != nil {
		return x.Tools
	}
	return nil
}

// Attestation with full details (returned by GetAttestation).
type Attestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttesterDid   string                 `protobuf:"bytes,2,opt,name=attester_did,json=attesterDid,proto3" json:"attester_did,omitempty"`
	ToolUri       string                 `protobuf:"bytes,3,opt,name=tool_uri,json=toolUri,proto3" json:"tool_uri,omitempty"`
	Outcome       string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,5,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{10}
}

func (x *Attestation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attestation) GetAttesterDid() string {
	if x != nil {
		return x.AttesterDid
	}
	return ""
}

func (x *Attestation) GetToolUri() string {
	if x != nil {
		return x.ToolUri
	}
	return ""
}

func (x *Attestation) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Attestation) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *Attestation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Attestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Attestation) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

// RedactedAttestation has the attester DID truncated to prevent enumeration.
type RedactedAttestation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttesterDidPrefix string                 `protobuf:"bytes,2,opt,name=attester_did_prefix,json=attesterDidPrefix,proto3" json:"attester_did_prefix,omitempty"` // First 16 chars of the DID.
	ToolUri           string                 `protobuf:"bytes,3,opt,name=tool_uri,json=toolUri,proto3" json:"tool_uri,omitempty"`
	Outcome           string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Claims            map[string]string      `protobuf:"bytes,5,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version           string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	IssuedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RedactedAttestation) Reset() {
	*x = RedactedAttestation{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactedAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactedAttestation) ProtoMessage() {}

func (x *RedactedAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactedAttestation.ProtoReflect.Descriptor instead.
func (*RedactedAttestation) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{11}
}

func (x *RedactedAttestation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RedactedAttestation) GetAttesterDidPrefix() string {
	if x != nil {
		return x.AttesterDidPrefix
	}
	return ""
}

func (x *RedactedAttestation) GetToolUri() string {
	if x != nil {
		return x.ToolUri
	}
	return ""
}

func (x *RedactedAttestation) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *RedactedAttestation) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *RedactedAttestation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RedactedAttestation) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

// ToolSummary is a tool entry in the top-tools leaderboard.
type ToolSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ToolUri           string                 `protobuf:"bytes,1,opt,name=tool_uri,json=toolUri,proto3" json:"tool_uri,omitempty"`
	Score             float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	TotalAttestations int32                  `protobuf:"varint,3,opt,name=total_attestations,json=totalAttestations,proto3" json:"total_attestations,omitempty"`
	UniqueAttesters   int32                  `protobuf:"varint,4,opt,name=unique_attesters,json=uniqueAttesters,proto3" json:"unique_attesters,omitempty"`
	SuccessRate       float64                `protobuf:"fixed64,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	FirstSeen         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastActive        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Provisional       bool                   `protobuf:"varint,8,opt,name=provisional,proto3" json:"provisional,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolSummary) Reset() {
	*x = ToolSummary{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSummary) ProtoMessage() {}

func (x *ToolSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSummary.ProtoReflect.Descriptor instead.
func (*ToolSummary) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{12}
}

func (x *ToolSummary) GetToolUri() string {
	if x != nil {
		return x.ToolUri
	}
	return ""
}

func (x *ToolSummary) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ToolSummary) GetTotalAttestations() int32 {
	if x != nil {
		return x.TotalAttestations
	}
	return 0
}

func (x *ToolSummary) GetUniqueAttesters() int32 {
	if x != nil {
		return x.UniqueAttesters
	}
	return 0
}

func (x *ToolSummary) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ToolSummary) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *ToolSummary) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *ToolSummary) GetProvisional() bool {
	if x != nil {
		return x.Provisional
	}
	return false
}

type RetractAttestationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attestation ID to retract.
	AttestationId string `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	// DID of the original attester (must match the stored attester_did).
	AttesterDid string `protobuf:"bytes,2,opt,name=attester_did,json=attesterDid,proto3" json:"attester_did,omitempty"`
	// Ed25519 signature over the canonical deletion payload:
	// {"action":"retract","attestation_id":"<id>","attester_did":"<did>"}
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractAttestationRequest) Reset() {
	*x = RetractAttestationRequest{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractAttestationRequest) ProtoMessage() {}

func (x *RetractAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractAttestationRequest.ProtoReflect.Descriptor instead.
func (*RetractAttestationRequest) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{13}
}

func (x *RetractAttestationRequest) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *RetractAttestationRequest) GetAttesterDid() string {
	if x != nil {
		return x.AttesterDid
	}
	return ""
}

func (x *RetractAttestationRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RetractAttestationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the retracted attestation.
	AttestationId string `protobuf:"bytes,1,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractAttestationResponse) Reset() {
	*x = RetractAttestationResponse{}
	mi := &file_api_trust_v1_trust_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractAttestationResponse) ProtoMessage() {}

func (x *RetractAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_trust_v1_trust_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractAttestationResponse.ProtoReflect.Descriptor instead.
func (*RetractAttestationResponse) Descriptor() ([]byte, []int) {
	return file_api_trust_v1_trust_proto_rawDescGZIP(), []int{14}
}

func (x *RetractAttestationResponse) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

var File_api_trust_v1_trust_proto protoreflect.FileDescriptor

const file_api_trust_v1_trust_proto_rawDesc = "" +
	"\n" +
	"\x18api/trust/v1/trust.proto\x12\x0esigil.trust.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x03\n" +
	"\x18SubmitAttestationRequest\x12%\n" +
	"\x0eattestation_id\x18\x01 \x01(\tR\rattestationId\x12!\n" +
	"\fattester_did\x18\x02 \x01(\tR\vattesterDid\x12\x19\n" +
	"\btool_uri\x18\x03 \x01(\tR\atoolUri\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12L\n" +
	"\x06claims\x18\x05 \x03(\v24.sigil.trust.v1.SubmitAttestationRequest.ClaimsEntryR\x06claims\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x127\n" +
	"\tissued_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x19SubmitAttestationResponse\x12%\n" +
	"\x0eattestation_id\x18\x01 \x01(\tR\rattestationId\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"0\n" +
	"\x13GetToolTrustRequest\x12\x19\n" +
	"\btool_uri\x18\x01 \x01(\tR\atoolUri\"\xd4\x03\n" +
	"\x14GetToolTrustResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12-\n" +
	"\x12total_attestations\x18\x02 \x01(\x05R\x11totalAttestations\x12)\n" +
	"\x10unique_attesters\x18\x03 \x01(\x05R\x0funiqueAttesters\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12;\n" +
	"\vlast_active\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x129\n" +
	"\n" +
	"first_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x12 \n" +
	"\vprovisional\x18\a \x01(\bR\vprovisional\x12;\n" +
	"\vcomputed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"computedAt\x12+\n" +
	"\x11versions_attested\x18\t \x01(\x05R\x10versionsAttested\x12%\n" +
	"\x0elatest_version\x18\n" +
	" \x01(\tR\rlatestVersion\">\n" +
	"\x15GetAttestationRequest\x12%\n" +
	"\x0eattestation_id\x18\x01 \x01(\tR\rattestationId\"W\n" +
	"\x16GetAttestationResponse\x12=\n" +
	"\vattestation\x18\x01 \x01(\v2\x1b.sigil.trust.v1.AttestationR\vattestation\"\xcf\x01\n" +
	"\x17ListAttestationsRequest\x12\x19\n" +
	"\btool_uri\x18\x01 \x01(\tR\atoolUri\x120\n" +
	"\x05after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05after\x122\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x8b\x01\n" +
	"\x18ListAttestationsResponse\x12G\n" +
	"\fattestations\x18\x01 \x03(\v2#.sigil.trust.v1.RedactedAttestationR\fattestations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"n\n" +
	"\x13ListTopToolsRequest\x12\x1f\n" +
	"\vwindow_days\x18\x01 \x01(\x05R\n" +
	"windowDays\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12 \n" +
	"\fmin_age_days\x18\x03 \x01(\x05R\n" +
	"minAgeDays\"I\n" +
	"\x14ListTopToolsResponse\x121\n" +
	"\x05tools\x18\x01 \x03(\v2\x1b.sigil.trust.v1.ToolSummaryR\x05tools\"\xe2\x02\n" +
	"\vAttestation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fattester_did\x18\x02 \x01(\tR\vattesterDid\x12\x19\n" +
	"\btool_uri\x18\x03 \x01(\tR\atoolUri\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12?\n" +
	"\x06claims\x18\x05 \x03(\v2'.sigil.trust.v1.Attestation.ClaimsEntryR\x06claims\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x127\n" +
	"\tissued_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x02\n" +
	"\x13RedactedAttestation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13attester_did_prefix\x18\x02 \x01(\tR\x11attesterDidPrefix\x12\x19\n" +
	"\btool_uri\x18\x03 \x01(\tR\atoolUri\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12G\n" +
	"\x06claims\x18\x05 \x03(\v2/.sigil.trust.v1.RedactedAttestation.ClaimsEntryR\x06claims\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x02\n" +
	"\vToolSummary\x12\x19\n" +
	"\btool_uri\x18\x01 \x01(\tR\atoolUri\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12-\n" +
	"\x12total_attestations\x18\x03 \x01(\x05R\x11totalAttestations\x12)\n" +
	"\x10unique_attesters\x18\x04 \x01(\x05R\x0funiqueAttesters\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x01R\vsuccessRate\x129\n" +
	"\n" +
	"first_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x12;\n" +
	"\vlast_active\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x12 \n" +
	"\vprovisional\x18\b \x01(\bR\vprovisional\"\x83\x01\n" +
	"\x19RetractAttestationRequest\x12%\n" +
	"\x0eattestation_id\x18\x01 \x01(\tR\rattestationId\x12!\n" +
	"\fattester_did\x18\x02 \x01(\tR\vattesterDid\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"C\n" +
	"\x1aRetractAttestationResponse\x12%\n" +
	"\x0eattestation_id\x18\x01 \x01(\tR\rattestationId2\xe3\x04\n" +
	"\fTrustService\x12h\n" +
	"\x11SubmitAttestation\x12(.sigil.trust.v1.SubmitAttestationRequest\x1a).sigil.trust.v1.SubmitAttestationResponse\x12Y\n" +
	"\fGetToolTrust\x12#.sigil.trust.v1.GetToolTrustRequest\x1a$.sigil.trust.v1.GetToolTrustResponse\x12_\n" +
	"\x0eGetAttestation\x12%.sigil.trust.v1.GetAttestationRequest\x1a&.sigil.trust.v1.GetAttestationResponse\x12e\n" +
	"\x10ListAttestations\x12'.sigil.trust.v1.ListAttestationsRequest\x1a(.sigil.trust.v1.ListAttestationsResponse\x12Y\n" +
	"\fListTopTools\x12#.sigil.trust.v1.ListTopToolsRequest\x1a$.sigil.trust.v1.ListTopToolsResponse\x12k\n" +
	"\x12RetractAttestation\x12).sigil.trust.v1.RetractAttestationRequest\x1a*.sigil.trust.v1.RetractAttestationResponseB&Z$sigil.dev/trust-service/api/v1;apiv1b\x06proto3"

var (
	file_api_trust_v1_trust_proto_rawDescOnce sync.Once
	file_api_trust_v1_trust_proto_rawDescData []byte
)

func file_api_trust_v1_trust_proto_rawDescGZIP() []byte {
	file_api_trust_v1_trust_proto_rawDescOnce.Do(func() {
		file_api_trust_v1_trust_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_trust_v1_trust_proto_rawDesc), len(file_api_trust_v1_trust_proto_rawDesc)))
	})
	return file_api_trust_v1_trust_proto_rawDescData
}

var (
	file_api_trust_v1_trust_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
	file_api_trust_v1_trust_proto_goTypes  = []any{
		(*SubmitAttestationRequest)(nil),   // 0: sigil.trust.v1.SubmitAttestationRequest
		(*SubmitAttestationResponse)(nil),  // 1: sigil.trust.v1.SubmitAttestationResponse
		(*GetToolTrustRequest)(nil),        // 2: sigil.trust.v1.GetToolTrustRequest
		(*GetToolTrustResponse)(nil),       // 3: sigil.trust.v1.GetToolTrustResponse
		(*GetAttestationRequest)(nil),      // 4: sigil.trust.v1.GetAttestationRequest
		(*GetAttestationResponse)(nil),     // 5: sigil.trust.v1.GetAttestationResponse
		(*ListAttestationsRequest)(nil),    // 6: sigil.trust.v1.ListAttestationsRequest
		(*ListAttestationsResponse)(nil),   // 7: sigil.trust.v1.ListAttestationsResponse
		(*ListTopToolsRequest)(nil),        // 8: sigil.trust.v1.ListTopToolsRequest
		(*ListTopToolsResponse)(nil),       // 9: sigil.trust.v1.ListTopToolsResponse
		(*Attestation)(nil),                // 10: sigil.trust.v1.Attestation
		(*RedactedAttestation)(nil),        // 11: sigil.trust.v1.RedactedAttestation
		(*ToolSummary)(nil),                // 12: sigil.trust.v1.ToolSummary
		(*RetractAttestationRequest)(nil),  // 13: sigil.trust.v1.RetractAttestationRequest
		(*RetractAttestationResponse)(nil), // 14: sigil.trust.v1.RetractAttestationResponse
		nil,                                // 15: sigil.trust.v1.SubmitAttestationRequest.ClaimsEntry
		nil,                                // 16: sigil.trust.v1.Attestation.ClaimsEntry
		nil,                                // 17: sigil.trust.v1.RedactedAttestation.ClaimsEntry
		(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	}
)
var file_api_trust_v1_trust_proto_depIdxs = []int32{
	15, // 0: sigil.trust.v1.SubmitAttestationRequest.claims:type_name -> sigil.trust.v1.SubmitAttestationRequest.ClaimsEntry
	18, // 1: sigil.trust.v1.SubmitAttestationRequest.issued_at:type_name -> google.protobuf.Timestamp
	18, // 2: sigil.trust.v1.GetToolTrustResponse.last_active:type_name -> google.protobuf.Timestamp
	18, // 3: sigil.trust.v1.GetToolTrustResponse.first_seen:type_name -> google.protobuf.Timestamp
	18, // 4: sigil.trust.v1.GetToolTrustResponse.computed_at:type_name -> google.protobuf.Timestamp
	10, // 5: sigil.trust.v1.GetAttestationResponse.attestation:type_name -> sigil.trust.v1.Attestation
	18, // 6: sigil.trust.v1.ListAttestationsRequest.after:type_name -> google.protobuf.Timestamp
	18, // 7: sigil.trust.v1.ListAttestationsRequest.before:type_name -> google.protobuf.Timestamp
	11, // 8: sigil.trust.v1.ListAttestationsResponse.attestations:type_name -> sigil.trust.v1.RedactedAttestation
	12, // 9: sigil.trust.v1.ListTopToolsResponse.tools:type_name -> sigil.trust.v1.ToolSummary
	16, // 10: sigil.trust.v1.Attestation.claims:type_name -> sigil.trust.v1.Attestation.ClaimsEntry
	18, // 11: sigil.trust.v1.Attestation.issued_at:type_name -> google.protobuf.Timestamp
	17, // 12: sigil.trust.v1.RedactedAttestation.claims:type_name -> sigil.trust.v1.RedactedAttestation.ClaimsEntry
	18, // 13: sigil.trust.v1.RedactedAttestation.issued_at:type_name -> google.protobuf.Timestamp
	18, // 14: sigil.trust.v1.ToolSummary.first_seen:type_name -> google.protobuf.Timestamp
	18, // 15: sigil.trust.v1.ToolSummary.last_active:type_name -> google.protobuf.Timestamp
	0,  // 16: sigil.trust.v1.TrustService.SubmitAttestation:input_type -> sigil.trust.v1.SubmitAttestationRequest
	2,  // 17: sigil.trust.v1.TrustService.GetToolTrust:input_type -> sigil.trust.v1.GetToolTrustRequest
	4,  // 18: sigil.trust.v1.TrustService.GetAttestation:input_type -> sigil.trust.v1.GetAttestationRequest
	6,  // 19: sigil.trust.v1.TrustService.ListAttestations:input_type -> sigil.trust.v1.ListAttestationsRequest
	8,  // 20: sigil.trust.v1.TrustService.ListTopTools:input_type -> sigil.trust.v1.ListTopToolsRequest
	13, // 21: sigil.trust.v1.TrustService.RetractAttestation:input_type -> sigil.trust.v1.RetractAttestationRequest
	1,  // 22: sigil.trust.v1.TrustService.SubmitAttestation:output_type -> sigil.trust.v1.SubmitAttestationResponse
	3,  // 23: sigil.trust.v1.TrustService.GetToolTrust:output_type -> sigil.trust.v1.GetToolTrustResponse
	5,  // 24: sigil.trust.v1.TrustService.GetAttestation:output_type -> sigil.trust.v1.GetAttestationResponse
	7,  // 25: sigil.trust.v1.TrustService.ListAttestations:output_type -> sigil.trust.v1.ListAttestationsResponse
	9,  // 26: sigil.trust.v1.TrustService.ListTopTools:output_type -> sigil.trust.v1.ListTopToolsResponse
	14, // 27: sigil.trust.v1.TrustService.RetractAttestation:output_type -> sigil.trust.v1.RetractAttestationResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_trust_v1_trust_proto_init() }
func file_api_trust_v1_trust_proto_init() {
	if File_api_trust_v1_trust_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_trust_v1_trust_proto_rawDesc), len(file_api_trust_v1_trust_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_trust_v1_trust_proto_goTypes,
		DependencyIndexes: file_api_trust_v1_trust_proto_depIdxs,
		MessageInfos:      file_api_trust_v1_trust_proto_msgTypes,
	}.Build()
	File_api_trust_v1_trust_proto = out.File
	file_api_trust_v1_trust_proto_goTypes = nil
	file_api_trust_v1_trust_proto_depIdxs = nil
}
