// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: trust.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrustService_SubmitAttestation_FullMethodName  = "/sigil.trust.v1.TrustService/SubmitAttestation"
	TrustService_GetToolTrust_FullMethodName       = "/sigil.trust.v1.TrustService/GetToolTrust"
	TrustService_GetAttestation_FullMethodName     = "/sigil.trust.v1.TrustService/GetAttestation"
	TrustService_ListAttestations_FullMethodName   = "/sigil.trust.v1.TrustService/ListAttestations"
	TrustService_ListTopTools_FullMethodName       = "/sigil.trust.v1.TrustService/ListTopTools"
	TrustService_RetractAttestation_FullMethodName = "/sigil.trust.v1.TrustService/RetractAttestation"
)

// TrustServiceClient is the client API for TrustService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TrustService provides tool trust queries and attestation submission.
//
// Privacy design:
//   - ListAttestations filters by tool, NOT by attester. Attester DIDs are
//     redacted in list responses to prevent cross-tool enumeration of usage
//     patterns.
//   - GetAttestation returns full details (including attester DID) for a
//     single attestation by ID, preserving independent verifiability.
//   - A future GetMyAttestations RPC (authenticated) can be added when needed.
type TrustServiceClient interface {
	// SubmitAttestation records a signed tool attestation.
	//
	// Timestamp acceptance window: issued_at must be within 5 minutes in the
	// future or 24 hours in the past relative to server time.
	//
	// Only did:key attesters are accepted initially.
	//
	// Rate limit: 50 attestations per DID per hour.
	SubmitAttestation(ctx context.Context, in *SubmitAttestationRequest, opts ...grpc.CallOption) (*SubmitAttestationResponse, error)
	// GetToolTrust returns the computed trust digest for a tool.
	// Unknown tools return a zero-value digest (not NOT_FOUND).
	GetToolTrust(ctx context.Context, in *GetToolTrustRequest, opts ...grpc.CallOption) (*GetToolTrustResponse, error)
	// GetAttestation retrieves a single attestation by ID with full details
	// including the attester DID (for independent verification).
	GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error)
	// ListAttestations returns attestations for a tool with attester DIDs
	// redacted to prevent enumeration.
	ListAttestations(ctx context.Context, in *ListAttestationsRequest, opts ...grpc.CallOption) (*ListAttestationsResponse, error)
	// ListTopTools returns tools ranked by trust score within a time window.
	ListTopTools(ctx context.Context, in *ListTopToolsRequest, opts ...grpc.CallOption) (*ListTopToolsResponse, error)
	// RetractAttestation soft-deletes an attestation. Only the original attester
	// can retract, verified by Ed25519 signature over a canonical deletion payload.
	RetractAttestation(ctx context.Context, in *RetractAttestationRequest, opts ...grpc.CallOption) (*RetractAttestationResponse, error)
}

type trustServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrustServiceClient(cc grpc.ClientConnInterface) TrustServiceClient {
	return &trustServiceClient{cc}
}

func (c *trustServiceClient) SubmitAttestation(ctx context.Context, in *SubmitAttestationRequest, opts ...grpc.CallOption) (*SubmitAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAttestationResponse)
	err := c.cc.Invoke(ctx, TrustService_SubmitAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) GetToolTrust(ctx context.Context, in *GetToolTrustRequest, opts ...grpc.CallOption) (*GetToolTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolTrustResponse)
	err := c.cc.Invoke(ctx, TrustService_GetToolTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) GetAttestation(ctx context.Context, in *GetAttestationRequest, opts ...grpc.CallOption) (*GetAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttestationResponse)
	err := c.cc.Invoke(ctx, TrustService_GetAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) ListAttestations(ctx context.Context, in *ListAttestationsRequest, opts ...grpc.CallOption) (*ListAttestationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttestationsResponse)
	err := c.cc.Invoke(ctx, TrustService_ListAttestations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) ListTopTools(ctx context.Context, in *ListTopToolsRequest, opts ...grpc.CallOption) (*ListTopToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopToolsResponse)
	err := c.cc.Invoke(ctx, TrustService_ListTopTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustServiceClient) RetractAttestation(ctx context.Context, in *RetractAttestationRequest, opts ...grpc.CallOption) (*RetractAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractAttestationResponse)
	err := c.cc.Invoke(ctx, TrustService_RetractAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrustServiceServer is the server API for TrustService service.
// All implementations must embed UnimplementedTrustServiceServer
// for forward compatibility.
//
// TrustService provides tool trust queries and attestation submission.
//
// Privacy design:
//   - ListAttestations filters by tool, NOT by attester. Attester DIDs are
//     redacted in list responses to prevent cross-tool enumeration of usage
//     patterns.
//   - GetAttestation returns full details (including attester DID) for a
//     single attestation by ID, preserving independent verifiability.
//   - A future GetMyAttestations RPC (authenticated) can be added when needed.
type TrustServiceServer interface {
	// SubmitAttestation records a signed tool attestation.
	//
	// Timestamp acceptance window: issued_at must be within 5 minutes in the
	// future or 24 hours in the past relative to server time.
	//
	// Only did:key attesters are accepted initially.
	//
	// Rate limit: 50 attestations per DID per hour.
	SubmitAttestation(context.Context, *SubmitAttestationRequest) (*SubmitAttestationResponse, error)
	// GetToolTrust returns the computed trust digest for a tool.
	// Unknown tools return a zero-value digest (not NOT_FOUND).
	GetToolTrust(context.Context, *GetToolTrustRequest) (*GetToolTrustResponse, error)
	// GetAttestation retrieves a single attestation by ID with full details
	// including the attester DID (for independent verification).
	GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error)
	// ListAttestations returns attestations for a tool with attester DIDs
	// redacted to prevent enumeration.
	ListAttestations(context.Context, *ListAttestationsRequest) (*ListAttestationsResponse, error)
	// ListTopTools returns tools ranked by trust score within a time window.
	ListTopTools(context.Context, *ListTopToolsRequest) (*ListTopToolsResponse, error)
	// RetractAttestation soft-deletes an attestation. Only the original attester
	// can retract, verified by Ed25519 signature over a canonical deletion payload.
	RetractAttestation(context.Context, *RetractAttestationRequest) (*RetractAttestationResponse, error)
	mustEmbedUnimplementedTrustServiceServer()
}

// UnimplementedTrustServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrustServiceServer struct{}

func (UnimplementedTrustServiceServer) SubmitAttestation(context.Context, *SubmitAttestationRequest) (*SubmitAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAttestation not implemented")
}
func (UnimplementedTrustServiceServer) GetToolTrust(context.Context, *GetToolTrustRequest) (*GetToolTrustResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolTrust not implemented")
}
func (UnimplementedTrustServiceServer) GetAttestation(context.Context, *GetAttestationRequest) (*GetAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttestation not implemented")
}
func (UnimplementedTrustServiceServer) ListAttestations(context.Context, *ListAttestationsRequest) (*ListAttestationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAttestations not implemented")
}
func (UnimplementedTrustServiceServer) ListTopTools(context.Context, *ListTopToolsRequest) (*ListTopToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopTools not implemented")
}
func (UnimplementedTrustServiceServer) RetractAttestation(context.Context, *RetractAttestationRequest) (*RetractAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetractAttestation not implemented")
}
func (UnimplementedTrustServiceServer) mustEmbedUnimplementedTrustServiceServer() {}
func (UnimplementedTrustServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrustServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrustServiceServer will
// result in compilation errors.
type UnsafeTrustServiceServer interface {
	mustEmbedUnimplementedTrustServiceServer()
}

func RegisterTrustServiceServer(s grpc.ServiceRegistrar, srv TrustServiceServer) {
	// If the following call panics, it indicates UnimplementedTrustServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrustService_ServiceDesc, srv)
}

func _TrustService_SubmitAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServiceServer).SubmitAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustService_SubmitAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServiceServer).SubmitAttestation(ctx, req.(*SubmitAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustService_GetToolTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServiceServer).GetToolTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustService_GetToolTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServiceServer).GetToolTrust(ctx, req.(*GetToolTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustService_GetAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServiceServer).GetAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustService_GetAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServiceServer).GetAttestation(ctx, req.(*GetAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustService_ListAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttestationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServiceServer).ListAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustService_ListAttestations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServiceServer).ListAttestations(ctx, req.(*ListAttestationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustService_ListTopTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServiceServer).ListTopTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustService_ListTopTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServiceServer).ListTopTools(ctx, req.(*ListTopToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustService_RetractAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetractAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServiceServer).RetractAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustService_RetractAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServiceServer).RetractAttestation(ctx, req.(*RetractAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrustService_ServiceDesc is the grpc.ServiceDesc for TrustService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrustService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sigil.trust.v1.TrustService",
	HandlerType: (*TrustServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAttestation",
			Handler:    _TrustService_SubmitAttestation_Handler,
		},
		{
			MethodName: "GetToolTrust",
			Handler:    _TrustService_GetToolTrust_Handler,
		},
		{
			MethodName: "GetAttestation",
			Handler:    _TrustService_GetAttestation_Handler,
		},
		{
			MethodName: "ListAttestations",
			Handler:    _TrustService_ListAttestations_Handler,
		},
		{
			MethodName: "ListTopTools",
			Handler:    _TrustService_ListTopTools_Handler,
		},
		{
			MethodName: "RetractAttestation",
			Handler:    _TrustService_RetractAttestation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trust.proto",
}
